- name: Update and upgrade
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 86400 #One day
    autoclean: yes
    autoremove: yes
#    lock_timeout: 120
  register: apt_upgrade_status
- debug:
    var: apt_upgrade_status
- name: Wait for upgrade to complete
  wait_for_connection:
    delay: 10
  when: apt_upgrade_status.changed
- name: Check if reboot needed
  stat: 
    path: /var/run/reboot-required
  register: reboot_required_marker_file
- debug:
    var: reboot_required_marker_file
- name: Reboot the machine
  reboot:
    reboot_timeout: 3600
  when: reboot_required_marker_file.stat.exists
- name: Wait for reboot to complete
  wait_for_connection:
    delay: 10
  when: reboot_required_marker_file.stat.exists