- name: update allowed hosts
  vars:
    common_ip_part: "{{ private_subnet | regex_replace('0\\/.+$', '') }}"
    nagios_server_ip: "{{common_ip_part}}{{hostvars[groups['nagios_servers'][0]]['nbr']}}"
  lineinfile:
    dest: /etc/nagios/nrpe.cfg
    regexp: allowed_hosts
    line: "allowed_hosts={{nagios_server_ip}}/32,127.0.0.1,::1"
  notify:
    - restart nrpe

- name: update nrpe server ip address (only open internal ports)
  vars:
    common_ip_part: "{{ private_subnet | regex_replace('0\\/.+$', '') }}"
    nrpe_server_ip: "{{common_ip_part}}{{nbr}}"
  lineinfile:
    dest: /etc/nagios/nrpe.cfg
    regexp: server_address
    line: "server_address={{ nrpe_server_ip }}"
  notify:
    - restart nrpe

- name: copy nrpe configuration
  vars:
        common_ip_part: "{{ private_subnet | regex_replace('0\\/.+$', '') }}"
        client_ip: "{{ common_ip_part }}{{ nbr }}"
  template:
    src: "{{ item }}"
    dest: /etc/nagios/nrpe.d/{{ item }}
    owner: root
    group: root
    mode: 0644
  with_items:
    - check_nrpe.cfg
  notify:
    - restart nrpe
