- name: Ensure /opt/altrusoft folder
  file: 
    path: /opt/altrusoft
    owner: root 
    group: root
    mode: 0755 
    state: directory

- name: Ensure /opt/altrusoft/lib folder
  file: 
    path: /opt/altrusoft/lib
    owner: root 
    group: root
    mode: 0755 
    state: directory

- name: Copy library files
  copy:
    src: "lib/{{ item }}"
    dest: /opt/altrusoft/lib/{{ item }}
    owner: root
    group: root
    mode: 0444
  with_items:
    - log_utils
    - lvm_utils
    - mount_utils
    - set_utils
    - string_utils

- name: Install yq
  copy:
    src: "usr_bin/yq_linux_amd64"
    dest: /usr/bin/yq
    owner: root
    group: root
    mode: 0755
